databases:
  - name: festify_db
    databaseName: festify_production
    user: festify_user

services:
  - type: web
    name: festify-backend
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server -e production"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: festify_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
